// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace com.iuixi.FreeJeck
{
	public class WebLog
	{
		public WebLog ()
		{
		}

		public static void Log(object msg)
		{
#if UNITY_WEBPLAYER
			Loom.DispatchToMainThread(()=>Application.ExternalCall("console.log", msg));
#else
			Debug.Log(msg);
#endif
		}

	}
}

