//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

namespace com.iuixi.FreeJeck
{
	public enum Direction{
		HOR,
		VIR,
	}
	public class Table<T, B> where B : TableCell<T>
	{
		private List<T> data;
		private int currentPage;
		private int cols;
		private int rows;
		private Direction direction;
		private float paddingX;
		private float paddingY;
		private float speed;
//		private List<B<T>> cells;
		private int maxPage;
		private bool isStable;
		/*
		public int Cols{
			get;
			set {

			}
		}*/
		
	/*	public void Render(int page)
		{
			if(page * cols * rows > data.Count)
			{
				page = maxPage;
			}
			//.....
			List<T> currentData = null;
			for (int i = 0; i < currentData.Count; i++) {
				cells[i].Render(currentData[i]);
				cells[i].destention = Vector3//i * (cells.CellWidth + paddingX) + paddingX;
			}
		}

		void Update()
		{
			//for///
			item.position += Item.destionation / speed * Time.deltaTime;
			if(cells[0].x < 0)
			{
				cells.
			}
		}*/
	}
}

